flags: {}
allow-different-user: true
extra-package-dbs: []
packages:
- '.'
- ./../CommonResources
- location:
    git: https://github.com/Palmik/bson-generic.git
    commit: e078def65d0dee1ea7e3205f445e47d5937851f3
extra-deps:
- bytestring-builder-0.10.8.1.0
- fast-logger-2.4.10
- hspec-2.4.1
- hspec-core-2.4.1
- hspec-discover-2.4.1
- hspec-expectations-0.8.2
- http-api-data-0.3.2
- mmorph-1.0.9
- persistent-2.6
- persistent-sqlite-2.6
- persistent-template-2.5.1.6
- servant-0.9.1.1
- servant-client-0.9.1.1
- servant-server-0.9.1.1
- unix-compat-0.4.3.1
- warp-3.2.11
- xml-conduit-1.4.0.4
resolver: lts-6.29
